# Generated by Django 2.2.5 on 2019-09-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
