# Generated by Django 2.2.5 on 2019-09-13 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('ambulance', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=tickets.models.random_string, max_length=200)),
                ('join_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('serve_doc', models.BooleanField(default=False)),
                ('serve_ambulance', models.BooleanField(default=False)),
                ('serve_hospital', models.BooleanField(default=False)),
                ('generation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('ambulance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ambulance.Ambulance')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitals.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.Patient')),
            ],
        ),
    ]
