# Generated by Django 2.2.5 on 2019-09-13 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('degree', models.CharField(default='MBBS', max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('join_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hospital', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='hospitals.Hospital')),
            ],
        ),
    ]
